#!/bin/sh

usage() {
    cat << EOF
Usage: $(basename ${0}) [ -c ] [ -h ] [ -o SCREEN ] [ -r ]

Available options:
-c      Copy outputs
-h      Print this help and exit
-o      Turn off display SCREEN
-r      Restore settings
EOF
}

read -rd '' SCREEN1 SCREEN2 <<<$(xrandr | grep -w connected | cut -d' ' -f1)

[[ $1 == "--help" ]] && usage && exit

while getopts "hrco:" arg; do
    case $arg in
        o)
            if [[ ${OPTARG} == "1" ]]; then
                DEVICE=${SCREEN1}
            elif [[ ${OPTARG} == "2" ]];then
                DEVICE=${SCREEN2}
            else
                echo "Unknown device"
                exit 1
            fi
            xrandr --output ${DEVICE} --off
            ;;
        r)
            xrandr --output ${SCREEN1} --auto
            xrandr --output ${SCREEN2} --auto --right-of ${SCREEN1}
            killall pw-loopback
            PAPE=$(grep wallpaper $HOME/memes.log | cut -d" " -f2)
            [[ -f ${PAPE} ]] && xwallpaper --zoom ${PAPE}
            ;;
        c)
            xrandr --output ${SCREEN2} --same-as ${SCREEN1}
            ;;
        h)
            usage
            exit
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [[ ${#} -eq 0 ]];then
    xrandr --auto
    pkill -x -0 pw-loopback || pw-loopback -n gameloop -C 'alsa_input.pci-0000_00_1f.3.analog-stereo' &disown
fi
