#!/bin/sh

PLAYLIST='heav'

if [[ -f "~/playlists/${1}" ]]; then
    PLAYLIST="${1}"
fi

args=(
    --aid=2 \
    --sid=2 \
    # --pause --reset-on-next-file=pause \
    # --speed=1.5 \
    --save-position-on-quit \
    --playlist="/home/alex/playlists/$PLAYLIST"
    --write-filename-in-watch-later-config
    )

mpv "${args[@]}"
