#!/bin/sh

pkill -0 transmission-da || (transmission-daemon && notify-send "Starting transmission daemon...")

count=0

until $(transmission-remote -l &>/dev/null) || [ ${count} -ge 8 ]
do
    sleep .5
    let count++
done

[[ ${count} -ge 8 ]] && (notify-send "Transmission"  "Could not start daemon"
canberra-gtk-play -i battery-low && exit 1)

NAME=$(echo ${@} | sed -n 's/.*&dn=\([^&]*\)&.*/\1/pi' | sed 's/%20/ /g;s/%26/\&/g;s/%5B/[/g;s/%5D/]/g;s/%28/(/g;s/%29/)/g')
TRM="st -e /bin/sh -c 'cat ~/.cache/wal/newseq; tremc -X'"

read -rd '' AWE <<- EOF
    local naughty = require('naughty')
    local awful = require('awful')
    naughty.notify({ icon = '/home/alex/Pictures/icons/download.png', title = 'Transmission-daemon', text = 'Adding ${NAME}', run = function () awful.spawn.with_shell("${TRM}") end, timeout = 10})
EOF

awesome-client "$AWE"

transmission-remote -a "$@"

